# Generated by Django 4.0.8 on 2022-11-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_borrowedhistory_remove_book_person_lent_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='book.category'),
        ),
    ]
