# Generated by Django 4.0.8 on 2022-12-01 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_remove_book_categories_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedhistory',
            name='person_lent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_lent_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('person_reserved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_reserved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
